# g++ test.cc -lsndfile -lfftw3 -lm
# g++ realtime_test.cc -lsndfile -lfftw3 -lportaudio -lm
# g++ realtime_playback_test.cc pa_ringbuffer.c -lsndfile -lfftw3 -lportaudio -lm
# g++ `pkg-config --cflags glfw3 glu` -o gl opengl_test.c `pkg-config --libs glfw3 glu` -lGLEW

# gcc -std=gnu99 -o test.out realtime_playback_test2.c pa_ringbuffer.c memutils.c -lsndfile -lfftw3 -lportaudio `pkg-config --cflags glfw3 glu` `pkg-config --libs glfw3 glu` -lGLEW -lm

# gcc -std=gnu99 -o test.out main.c visualizer.c partitioner.c pa_ringbuffer.c memutils.c -lsndfile -lfftw3 -lportaudio `pkg-config --cflags glfw3 glu` `pkg-config --libs glfw3 glu` -lGLEW -lm

